[package]
name = "tcp_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
ctrlc = "3.2.3"
rpassword = "7.0.0"
